apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: osem2sem2o/todo-app:latest
        ports:
        - containerPort: 3000